version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env.prod
    volumes:
      - ./backend/:/usr/src/backend/
      - media_volume:/usr/src/backend/mediafiles
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - media_volume:/usr/src/backend/mediafiles
    depends_on:
      - backend

volumes:
  postgres_data:
  media_volume:

