# Generated by Django 4.2.15 on 2024-08-28 06:16

import bookshelf.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('book', 'Book'), ('show', 'TV Show'), ('film', 'Film'), ('app', 'App'), ('article', 'Article')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=bookshelf.models.get_file_path)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='bookshelf.media')),
            ],
        ),
    ]
