# Generated by Django 4.2.15 on 2024-08-18 11:30

import django.contrib.postgres.fields
from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('developer', 'Developer'), ('mentor', 'Mentor'), ('activist', 'Activist')], max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=portfolio.models.get_file_path_image)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=portfolio.models.get_file_path_logo)),
                ('date', models.CharField(max_length=100)),
                ('tools', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('quote', models.TextField(blank=True, null=True)),
                ('attribution', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
