# Generated by Django 4.2.15 on 2024-08-26 05:21

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=portfolio.models.get_file_path_image)),
                ('project_type', models.CharField(choices=[('developer', 'Developer'), ('mentor', 'Mentor'), ('activist', 'Activist')], max_length=10)),
                ('slug', models.SlugField(max_length=100)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
        ),
    ]
